// Generated by CoffeeScript 1.6.3
var beep, body, clock, controls, countDown, counter, description, exercises, nextWorkout, progressPoints, reset, restInterval, startWorkout, welcome, workInterval;

welcome = document.getElementById("welcome");

clock = document.getElementById("counter");

body = document.getElementsByTagName("body")[0];

description = document.getElementById("description");

controls = document.getElementById("controls");

progressPoints = document.getElementById("progress").children;

workInterval = 30;

restInterval = 10;

exercises = ['Jumping Jacks', 'Wall Sit', 'Push-ups', 'Sit-ups', 'Step-ups', 'Squats', 'Tricep Dips', 'Plank', 'High Knees', 'Lunges', 'Push-ups and Rotation', 'Side Plank'];

beep = new Audio("beep.wav");

counter = document.getElementById("counter");

countDown = function(i, nextAction) {
  var skip, timeout;
  if (i <= 0 || skip) {
    skip = false;
    beep.play();
    nextAction();
    return;
  }
  counter.innerHTML = i;
  return timeout = window.setTimeout(function() {
    return countDown(i - 1, nextAction);
  }, 1000);
};

reset = function() {
  var current, i, skip, _i, _ref;
  welcome.style.display = 'block';
  counter.style.display = 'none';
  description.style.display = 'none';
  controls.style.display = 'none';
  body.style.background = '#3498db';
  for (i = _i = 0, _ref = progressPoints.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    progressPoints[i].className = ' ';
  }
  skip = true;
  return current = 0;
};

startWorkout = function() {
  var current, skip;
  description.style.display = 'block';
  welcome.style.display = 'none';
  counter.style.display = 'block';
  controls.style.display = 'block';
  current = 0;
  skip = false;
  return rest();
};

nextWorkout = function() {
  if (!exercises[current]) {
    reset();
    return;
  }
  body.style.background = "#e74c3c";
  description.innerHTML = exercises[current];
  countDown(workInterval, rest);
  progressPoints[current].className = 'done';
  return current++;
};
